### ISSUE TITLE
Something wrong with the dates it create 

### ISSUE THREAD

**Issue by sellinios** [earajr/GFS_plotting#5]
I have managed to run it, but it is 2021/01/11 04:00 in the morning, and it creates 2021011118 folder, I believe it trying to download GFS that is not there yet.

**Comment by earajr** [comment]
Is that local time or UTC?

The get_GFS_operational.sh script uses the bash date function with the -u argument to specify UTC time. Then the latest likely available GFS initialisation is identified and the date and time updated. I suspect you are running the script at a time between 0000 and 0259 UTC. The issue is caused by the fact that there is a missing line in the the script that doesn't update the date to yesterdays date when the hour selected is before 3 UTC, but the hour is modified to 18.

To fix add this line after line 35 (within the elseif statement) in the get_GFS_operational.sh script.

YYYYMMDD=`date -u --date='yesterday' +%Y%m%d`

I would recommend running the script at a time when GFS data is newly available too (0430 UTC would get you the 00 GFS initialisation).

**Comment by earajr** [comment]
This has now been rectified in the repository.
